name: Cypress Tests (Manual Trigger)

on:
  workflow_dispatch:  # Runs only when manually triggered

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker BuildKit
        run: |
          export DOCKER_BUILDKIT=1
          docker version

      - name: Create .env file from GitHub Secrets
        run: |
          echo "DB_USERNAME=${{ secrets.DB_USERNAME }}" >> .env
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
          echo "DB_PORT=${{ secrets.DB_PORT }}" >> .env

      - name: Build Docker Containers
        run: docker compose up -d --build

      - name: Wait for the app to be ready
        run: sleep 15  # Ensures the app is ready before running tests

      - name: Run Cypress Tests
        run: docker compose --profile testing run --rm cypress

      - name: Stop Containers
        run: docker compose down

      - name: Upload Cypress Screenshots and Videos
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-results
          path: |
            cypress/screenshots
            cypress/videos
